### ISSUE TITLE
Discrepancy in POST request payload format

### ISSUE THREAD

**Issue by shawnhind** [phpclassic/php-shopify#35]
Shopify API docs specify that JSON payload should be in this form:
`{
  "recurring_application_charge": {
    "name": "Super Duper Plan",
    "price": 10.0,
    "return_url": "http://super-duper.shopifyapps.com"
  }
}`

This library however, expects this form: 
`{
    "name": "Super Duper Plan",
    "price": 10.0,
    "return_url": "http://super-duper.shopifyapps.com"
}`

Basically the library expects you to leave out the outer array/JSON element.  I think it would be better to accept it either way and just check if the outer object is there or to indicate more clearly in the documentation not to include the outer object.

**Comment by tareqtms** [comment]
Good suggestion, we will look into it for a later version.

**Comment by tareqtms** [comment]
@shawnhind 
I am thinking, the current way will be good for maintaining. Because if we allow both ways, it will confuse the users to choose the better option. Also, the keys need to be provided accurately in a plural form, so there will be more ways to face issues by making a mistake here. 
But as you suggested, we should mention it clearly in the documentation that we don't expect the outer part of the array. 
Btw, thanks for your support.
