### ISSUE TITLE
Handling errors

### ISSUE THREAD

**Issue by devkaizenclicks** [phpclassic/php-shopify#88]
How does status codes 502, 503, 504 from shopify will be manifested, as exception?
Regards,

**Comment by tareqtms** [comment]
Currently, if the response code is anything other than 200 and 201, it will through ApiException if the errors are defined by the response (from Shopify). Otherwise, it will throw a CurlException, assuming it as a failure to send the Curl request properly.
We are open to suggestions and/or pull requests from you if you have a better idea.

**Comment by devkaizenclicks** [comment]
Thank you very much.
